### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by jryom** [stefanvictora/hue-scheduler#7]
Great project, thanks a lot for making and maintaining it 🙏🏻 

I'd just suggest that you make it available as a docker image. I run all my home automation/media server stuff as docker containers via docker-compose, which makes it super easy to handle updates and related files for each running container. I think publishing this as a docker image would make it easier for new users to jump in and get started :) 

Thanks again 💡

**Comment by cswrd** [comment]
In the meantime, this is my way of running it within a container. I do all of this with portainer web app on my NAS.

**Dockerfile** (Create the image):
```Containerfile
FROM openjdk:latest
WORKDIR /app
ADD https://github.com/stefanvictora/hue-scheduler/releases/download/v0.9.0/hue-scheduler.jar /app
```

**Docker Compose yaml**:
```yaml
version: '3'

services:
  my-hue-scheduler:
    image: hue-scheduler:0.9.0
    container_name: "hue-scheduler"
    environment:
     - TZ=Europe/Berlin
    dns:
      - <router IP>
    network_mode: "bridge"
    volumes:
      - <host_path>:/etc/opt/hue-scheduler/
    command: java -jar hue-scheduler.jar <hue bridge IP> <api-token> --lat=<lat> --long=<long> --elevation=<elevation> /etc/opt/hue-scheduler/schedules.txt
    deploy:
      restart_policy:
          condition: on-failure
```
